# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 14:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20181007_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
