# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20181008_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='images_array',
            new_name='images',
        ),
    ]
